[package]
name = "spark_studio"
version.workspace = true
edition.workspace = true

[dependencies]
spark_assets = { workspace = true }
spark_audio = { workspace = true }
spark_render = { workspace = true }
spark_text = { workspace = true }
spark_ui = { workspace = true }
winit = { workspace = true }
